import Header from '@/components/Header';
import Main from '@/components/Main';
import { useAuth } from '@/context/AuthContext';
import Head from 'next/head';

export default function Home() {
  const { user, signUp } = useAuth();
  return (
    <>
      <Head>
        <title>Chata</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="p-0 bg-view bg-cover bg-fixed min-h-[100vh]  h-[100%] flex flex-col align-middle">
        {user && <Header />}
        <Main />
      </div>
    </>
  );
}
